'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {GraduationCap,Plus,Upload,Download,BookOpen,FileText,CheckCircle2,Search,Printer,LoaderCircle,AlertCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {calculate,rollKey,validateSubject,type Subject,bands} from '@/lib/grades';
import {extractPdf} from '@/lib/pdf';
const fmt=(n:number|null|undefined,d=2)=>n==null?'—':n.toFixed(d);
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function csv(name:string,head:string[],rows:unknown[][]){const cell=(x:unknown)=>{let s=x==null?'':String(x);if(/^[=+@\-]/.test(s)&&typeof x!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+[head,...rows].map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
type Actual={term:number;subject:string;credit:number;grade:string;point:number};
export default function Dashboard(){
 const [subjects,setSubjects]=useState<Subject[]>([]),[actual,setActual]=useState<Actual[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [student,setStudent]=useState(''),[term,setTerm]=useState('all'),[tab,setTab]=useState('report'),[subjectId,setSubjectId]=useState('SCAS'),[search,setSearch]=useState(''),[basis,setBasis]=useState('estimated');
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Subject|null>(null),[name,setName]=useState(''),[credit,setCredit]=useState('1'),[courseTerm,setCourseTerm]=useState('4'),[file,setFile]=useState<File|null>(null),[parsed,setParsed]=useState<Awaited<ReturnType<typeof extractPdf>>|null>(null),[busy,setBusy]=useState(false),[uploadError,setUploadError]=useState('');
 const generation=useRef(0);
 async function load(){setLoading(true);setError('');try{const response=await fetch('/api/subjects',{cache:'no-store'});const data=await response.json() as {subjects:Subject[];actual:Actual[];error?:string};if(!response.ok)throw Error(data.error);setSubjects(data.subjects);setActual(data.actual);const roster=data.subjects.flatMap((s:Subject)=>s.rows);const mine=roster.find((r:any)=>rollKey(r.roll)==='41221')??roster[0];setStudent(v=>v||(mine?mine.name+' · '+mine.roll:''));}catch(e){setError(e instanceof Error?e.message:'Could not load marks.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const roster=useMemo(()=>{const map=new Map<string,string>();for(const s of subjects)for(const r of s.rows)if(!map.has(rollKey(r.roll)))map.set(rollKey(r.roll),r.name+' · '+r.roll);return [...map.values()].sort();},[subjects]);
 const key=rollKey(student.split(' · ')[1]??''),mine=key==='41221';
 const report=useMemo(()=>subjects.map(s=>({...s,result:calculate(s.rows).find(r=>rollKey(r.roll)===key)})).sort((a,b)=>a.term-b.term||a.name.localeCompare(b.name)),[subjects,key]);
 const visible=report.filter(s=>term==='all'||s.term===Number(term)),graded=visible.filter(s=>s.result?.point!=null&&s.credit>0),credits=graded.reduce((a,s)=>a+s.credit,0),cgpa=credits?graded.reduce((a,s)=>a+s.credit*s.result!.point!,0)/credits:null;
 const actualVisible=actual.filter(r=>term==='all'||r.term===Number(term)),actualCredit=actualVisible.reduce((s,r)=>s+r.credit,0),actualGpa=actualCredit?actualVisible.reduce((s,r)=>s+r.credit*r.point,0)/actualCredit:null,recorded=basis==='recorded'&&mine;
 const available=visible.filter(s=>s.result?.percentile!=null),avgPercent=available.length?available.reduce((a,s)=>a+s.result!.percentile!,0)/available.length:null;
 const terms=[...new Set(subjects.map(s=>s.term))].sort();
 const termMetrics=terms.map(t=>{const list=report.filter(s=>s.term===t),have=list.filter(s=>s.result?.point!=null&&s.credit>0),c=have.reduce((a,s)=>a+s.credit,0),a=actual.filter(r=>r.term===t),ac=a.reduce((s,r)=>s+r.credit,0);return {term:t,count:recorded?a.length:have.length,total:list.length,gpa:recorded?(ac?a.reduce((s,r)=>s+r.credit*r.point,0)/ac:null):(c?have.reduce((a,s)=>a+s.credit*s.result!.point!,0)/c:null)};});
 const subject=subjects.find(s=>s.id===subjectId)??subjects[0],subjectRows=subject?calculate(subject.rows):[],filtered=subjectRows.filter(r=>(r.name+' '+r.roll).toLowerCase().includes(search.toLowerCase()));
 const strongest=graded.length?[...graded].sort((a,b)=>b.result!.percentile!-a.result!.percentile!)[0]:null,gpa=recorded?actualGpa:cgpa;
 function start(s:Subject|null){generation.current++;setEditing(s);setName(s?.name??'');setCredit(String(s?.credit??1));setCourseTerm(String(s?.term??(term==='all'?4:term)));setFile(null);setParsed(null);setUploadError('');setBusy(false);setOpen(true);}
 async function upload(f:File|undefined){if(!f)return;const g=++generation.current;setFile(f);setParsed(null);setUploadError('');setBusy(true);try{if(f.size>20*1024*1024)throw Error('Choose a PDF smaller than 20 MB.');const p=await extractPdf(f);if(g!==generation.current)return;setParsed(p);if(!name)setName(/SCAS/i.test(f.name)?'SCAS':p.course??'');if(p.issues.length)setUploadError(p.issues.join(' '));}catch(e){if(g===generation.current)setUploadError(e instanceof Error?e.message:'Could not read this PDF.');}finally{if(g===generation.current)setBusy(false);}}
 async function save(){setUploadError('');setBusy(true);try{if(!editing&&!parsed)throw Error('Upload the marks PDF for this subject.');if(file&&(!parsed||parsed.issues.length))throw Error('The PDF has incomplete rows. Correct the sheet and upload again.');if(subjects.some(s=>s.name.trim().toLowerCase()===name.trim().toLowerCase()&&s.term===Number(courseTerm)&&s.id!==editing?.id))throw Error('This subject already exists. Use its Edit / upload PDF button.');if(!credit.trim())throw Error('Enter the credit value.');const data:Subject={id:editing?.id??crypto.randomUUID(),name:name.trim(),credit:Number(credit),term:Number(courseTerm),columns:parsed?.columns??editing!.columns,rows:parsed?.rows??editing!.rows,source:file?.name??editing?.source??'',updatedAt:null};validateSubject(data);const form=new FormData();form.append('subject',JSON.stringify(data));if(file)form.append('pdf',file);const response=await fetch('/api/subjects',{method:'POST',body:form});const result=await response.json() as {subject:Subject;error?:string};if(!response.ok)throw Error(result.error);setSubjects(v=>[...v.filter(s=>s.id!==result.subject.id),result.subject]);setSubjectId(result.subject.id);setOpen(false);setNotice(data.name+' saved. The report card has been updated.');}catch(e){setUploadError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 function exportSubject(){if(subject)csv(subject.name,['Section','Roll No','Name',...subject.columns,'Total','Rank','Z-Score','Percentile Rank','Grade','Grade Point'],subjectRows.map(r=>[r.section,r.roll,r.name,...r.components,r.total,r.rank,r.z,r.percentile,r.grade,r.point]));}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const abort=new AbortController();Promise.resolve(context.registerTool({name:'select_report_student',description:'Select a student by roll number and show their report card.',inputSchema:{type:'object',properties:{roll:{type:'string'}},required:['roll'],additionalProperties:false},execute:async(input:{roll:string})=>{if(typeof input?.roll!=='string')throw Error('Roll number is required.');const target=roster.find(r=>rollKey(r.split(' · ')[1])===rollKey(input.roll));if(!target)throw Error('Student not found.');setStudent(target);setTab('report');return {student:target};}},{signal:abort.signal})).catch(console.error);return ()=>abort.abort();},[roster]);
 return <div className="app"><header className="topbar"><a className="brand" href="/"><span className="brandicon"><GraduationCap size={25}/></span><span>ACADEMIC DESK<small>IIM Lucknow</small></span></a><div className="header-right"><span>Personal workspace</span><span className="avatar">SA</span></div></header><main>
 <div className="page-title"><div><div className="eyebrow">YOUR ACADEMIC PICTURE</div><h1>Report Card Generator<span>.</span></h1><p>Every subject. Every term. One clear view.</p></div><Button className="primary" onClick={()=>start(null)}><Plus size={18}/>Add subject</Button></div>
 {error&&<div role="alert" className="alert"><AlertCircle size={18}/>{error}<Button variant="outline" onClick={load}>Retry</Button></div>}{notice&&<div role="status" className="success"><CheckCircle2 size={18}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
 <div className="controls"><div className="student-picker"><label>Student</label><Combobox items={roster} value={student||null} onValueChange={v=>{if(v)setStudent(v);}}><ComboboxInput placeholder="Search name or roll number" aria-label="Select student"/><ComboboxContent><ComboboxEmpty>No students found.</ComboboxEmpty><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><div><label>Term</label><Choice value={term} onChange={setTerm} label="Filter term" items={[{value:'all',label:'All terms'},...terms.map(t=>({value:String(t),label:'Term '+t}))]}/></div><div className="report-actions"><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Print report</Button></div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="view-tabs"><TabsTrigger value="report"><GraduationCap size={17}/>Report card</TabsTrigger><TabsTrigger value="subjects"><BookOpen size={17}/>Subject sheets <span>{subjects.length}</span></TabsTrigger></TabsList>
 <TabsContent value="report">{loading?<div className="loading"><LoaderCircle className="spin"/>Loading your marks…</div>:<>
 <div className="overview"><section className="hero-card"><div className="hero-top"><div><span className="eyebrow">{recorded?'RECORDED GRADES':'PERCENTILE-BASED ESTIMATE'}</span><h2>{student.split(' · ')[0]||'Select a student'}</h2><p>{student.split(' · ')[1]} <span> / </span>{term==='all'?'All available terms':'Term '+term}</p></div><GraduationCap size={42} strokeWidth={1}/></div><div className="hero-bottom"><div><span className="gpa">{fmt(gpa)}</span><span className="out-of"> / 10</span><div className="gpa-label">{term==='all'?'Cumulative GPA':'Term GPA'} over available graded credits</div></div><div className="gpa-ring" style={{background:'conic-gradient(#b2f268 '+((gpa??0)*36)+'deg,#39525a 0deg)'}}><span>{fmt(gpa)}<small>GPA / 10</small></span></div></div>{mine&&<div className="basis"><button onClick={()=>setBasis('estimated')} className={!recorded?'selected':''}>Estimated grades</button><button onClick={()=>setBasis('recorded')} className={recorded?'selected':''}>Recorded grades · Terms 1–3</button></div>}</section>
 <div className="mini-cards"><section className="mini"><span className="mini-icon"><BookOpen size={20}/></span><div><span>Graded subjects</span><strong>{recorded?actualVisible.length:graded.length}<small> / {recorded?actualVisible.length:visible.length}</small></strong></div></section><section className="mini"><span className="mini-icon purple"><GraduationCap size={20}/></span><div><span>Credits included</span><strong>{fmt(recorded?actualCredit:credits)}</strong></div></section><section className="mini"><span className="mini-icon amber"><FileText size={20}/></span><div><span>Average percentile</span><strong>{recorded?'—':avgPercent==null?'—':fmt(avgPercent*100,1)+'%'}</strong></div></section></div></div>
 <div className="mid-grid"><section className="panel"><div className="section-title"><div><h3>Term performance</h3><p>Credit-weighted GPA across available subjects</p></div><span className="quiet">OUT OF 10</span></div><div className="term-bars">{termMetrics.map(m=><div className="term-bar" key={m.term}><strong>{fmt(m.gpa)}</strong><div className="bar-track"><div style={{height:((m.gpa??0)*10)+'%'}}/></div><span>Term {m.term}</span><small>{m.count}{!recorded&&'/'+m.total} subjects</small></div>)}</div></section><section className="panel insight"><span className="eyebrow">ESTIMATED SUBJECT SNAPSHOT</span><h3>{strongest?.name??'No graded subjects yet'}</h3><p>{strongest?'Your highest percentile among the selected subjects.':'Upload a marks PDF to build your report.'}</p><div className="snapshot"><span className="grade-big">{strongest?.result?.grade??'—'}</span><div><strong>{strongest?fmt(strongest.result!.percentile!*100,1)+'%':'—'}</strong><span>percentile</span></div></div><div className="insight-note">{strongest?'Rank '+strongest.result!.rank+' of '+strongest.rows.length+' students':'Results update after each upload.'}</div></section></div>
 <section className="panel report-table"><div className="section-title"><div><h3>{recorded?'Recorded subject grades':'Subject report card'}</h3><p>{recorded?'Your recorded Term 1–3 grades from the workbook.':'Add a subject, set its credits, and upload its marks PDF here.'}</p></div><Button variant="outline" onClick={()=>recorded?csv('Recorded_Report_Card',['Term','Subject','Credit','Grade','Grade Point'],actualVisible.map(r=>[r.term,r.subject,r.credit,r.grade,r.point])):csv('Report_Card',['Term','Subject','Credit','Total','Rank','Cohort','Z-Score','Percentile Rank','Grade','Grade Point'],visible.map(s=>[s.term,s.name,s.credit,s.result?.total,s.result?.rank,s.rows.length,s.result?.z,s.result?.percentile,s.result?.grade,s.result?.point]))}><Download size={16}/>Export CSV</Button></div><div className="table-scroll"><Table><TableHeader><TableRow>{(recorded?['Subject','Term','Credit','Grade','Grade point']:['Subject','Term','Credit','Total marks','Rank / cohort','Percentile','Grade','Grade point','Marks PDF']).map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{recorded?actualVisible.map((r,i)=><TableRow key={i}><TableCell className="subject-name">{r.subject}</TableCell><TableCell>{r.term}</TableCell><TableCell>{r.credit}</TableCell><TableCell><span className="grade-chip">{r.grade}</span></TableCell><TableCell>{r.point}</TableCell></TableRow>):visible.map(s=><TableRow key={s.id}><TableCell className="subject-name"><button onClick={()=>{setSubjectId(s.id);setTab('subjects');}}>{s.name}</button>{!s.result&&<small>Student absent from sheet</small>}</TableCell><TableCell>{s.term}</TableCell><TableCell>{s.credit}</TableCell><TableCell>{fmt(s.result?.total)}</TableCell><TableCell>{s.result?s.result.rank+' / '+s.rows.length:'—'}</TableCell><TableCell>{s.result?.percentile!=null?fmt(s.result.percentile*100,1)+'%':'—'}</TableCell><TableCell><span className={'grade-chip '+((s.result?.point??6)<=4?'low':(s.result?.point??0)>=8?'high':'')}>{s.result?.grade??'—'}</span></TableCell><TableCell>{s.result?.point??'—'}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>start(s)}><Upload size={14}/>Edit / upload PDF</Button></TableCell></TableRow>)}</TableBody></Table></div><button className="add-row" onClick={()=>start(null)}><Plus size={17}/>Add subject and upload marks</button></section>
 <details className="method"><summary>How grades are calculated</summary><p>Rank follows your RANK.EQ + COUNTIF rule. Ties use the source row order. Z-score uses population standard deviation. Exclusive percentile rank uses the first tied position and Excel’s default three decimal precision. GPA includes available graded subjects with positive credits. A zero-variance cohort cannot produce a Z-score or a grade.</p><div className="bands">{bands.map(b=><div key={b[1]}><strong>{b[1]}</strong><span>≥ {fmt(b[0]*100,2)}%</span><small>{b[2]} points</small></div>)}</div><p>Uploads support text-based PDFs with PGP/41 roll numbers. Scanned PDFs need OCR before upload. Each subject is graded against its own cohort.</p></details></>}</TabsContent>
 <TabsContent value="subjects"><section className="panel sheets"><div className="section-title"><div><h3>Subject sheet</h3><p>{subject?.source}{subject?.updatedAt?' · Updated '+new Date(subject.updatedAt).toLocaleDateString():''}</p></div><Button variant="outline" onClick={exportSubject}><Download size={16}/>Export CSV</Button></div><div className="sheet-controls"><Choice label="Select subject sheet" value={subject?.id??''} onChange={setSubjectId} items={subjects.map(s=>({value:s.id,label:s.name+' · Term '+s.term}))}/><div className="sheet-search"><Search size={16}/><Input aria-label="Search subject students" placeholder="Find a student…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="sheet-stats"><span><strong>{subjectRows.length}</strong> students</span><span><strong>{fmt(subjectRows[0]?.average)}</strong> class average</span><span><strong>{subject?.credit??0}</strong> credits</span><span>Term {subject?.term}</span></div><div className="table-scroll"><Table><TableHeader><TableRow>{['Section','Roll No.','Name',...(subject?.columns??[]),'Total','Rank','Z-score','Percentile','Grade','Grade point'].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(r=><TableRow key={r.roll} className={rollKey(r.roll)===key?'student-highlight':''}><TableCell>{r.section||'—'}</TableCell><TableCell>{r.roll}</TableCell><TableCell className="subject-name">{r.name}</TableCell>{r.components.map((n,i)=><TableCell key={i}>{fmt(n)}</TableCell>)}<TableCell><strong>{fmt(r.total)}</strong></TableCell><TableCell>{r.rank}</TableCell><TableCell>{fmt(r.z)}</TableCell><TableCell>{r.percentile===null?'—':fmt(r.percentile*100,1)+'%'}</TableCell><TableCell><span className="grade-chip">{r.grade??'—'}</span></TableCell><TableCell>{r.point??'—'}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<p className="empty">No students match this search.</p>}</div></section></TabsContent></Tabs><footer><span>Academic Desk</span><span>{subjects.length} subjects from visible and hidden workbook sheets</span></footer></main>
 <Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);if(!v)generation.current++;}}}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>{editing?'Update subject':'Add a subject'}</DialogTitle><DialogDescription>Enter the subject details and upload its marks PDF. Grades and report cards update when you save.</DialogDescription></DialogHeader><div className="form-grid"><label className="wide">Subject name<Input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. SCAS" maxLength={100}/></label><label>Credits<Input type="number" min="0" max="20" step="0.25" value={credit} onChange={e=>setCredit(e.target.value)}/></label><div><label>Term</label><Choice label="Subject term" value={courseTerm} onChange={setCourseTerm} items={[1,2,3,4,5,6].map(t=>({value:String(t),label:'Term '+t}))}/></div></div><label className="upload-box"><Upload size={28}/><strong>{busy?'Reading your PDF…':file?.name??'Upload marks PDF'}</strong><span>Text-based result sheet · up to 20 MB</span><input disabled={busy} type="file" accept="application/pdf,.pdf" onChange={e=>void upload(e.target.files?.[0])}/></label>{editing&&!file&&<p className="quiet">Current sheet: {editing.rows.length} students. A new PDF replaces the marks. Name and credits can be updated without a PDF.</p>}{uploadError&&<div className="alert" role="alert">{uploadError}</div>}{parsed&&<div className="import-preview"><div className="preview-title"><CheckCircle2 size={17}/><strong>{parsed.rows.length} students extracted</strong><span>{parsed.pages} pages</span></div><label>Component headings</label><div className="component-inputs">{parsed.columns.map((c,i)=><Input key={i} aria-label={'Component '+(i+1)+' heading'} value={c} onChange={e=>setParsed(p=>p?{...p,columns:p.columns.map((h,j)=>j===i?e.target.value:h)}:p)}/>)}</div><div className="table-scroll"><Table><TableHeader><TableRow>{['Roll No.','Name','Total','Est. grade'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{calculate(parsed.rows).slice(0,5).map(r=><TableRow key={r.roll}><TableCell>{r.roll}</TableCell><TableCell>{r.name}</TableCell><TableCell>{r.total}</TableCell><TableCell>{r.grade}</TableCell></TableRow>)}</TableBody></Table></div><p>First 5 rows shown. All extracted students will be saved.</p></div>}<div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy||(!editing&&!parsed)||!!parsed?.issues.length} onClick={save}>{busy?<LoaderCircle size={16} className="spin"/>:<CheckCircle2 size={16}/>}Save subject</Button></div></DialogContent></Dialog>
 </div>;
}
