import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const sample=process.argv[2];if(!sample)throw Error('Pass the SCAS sample PDF.');
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'marks-backend-')),base='http://127.0.0.1:5101',headers={Authorization:'Bearer test-access-code',Origin:'https://sampurnanandofficial1.github.io'};let child;
async function start(){child=spawn(process.execPath,['--experimental-strip-types','backend/server.mjs'],{env:{...process.env,PORT:'5101',ACCESS_CODE:'test-access-code',DATA_DIR:temp},stdio:['ignore','pipe','inherit']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server did not start')),10000);child.stdout.once('data',()=>{clearTimeout(timer);resolve();});child.once('exit',code=>reject(Error('Server exited '+code)));});}
async function stop(){const done=new Promise(r=>child.once('exit',r));child.kill();await done;}
try{
 await start();assert.equal((await fetch(base+'/api/subjects')).status,401);const response=await fetch(base+'/api/subjects',{headers});assert.equal(response.status,200);assert.equal(response.headers.get('access-control-allow-origin'),headers.Origin);const data=await response.json();assert.equal(data.subjects.length,26);const qam=data.subjects.find(s=>s.name==='QAM-3');const legacy=new FormData();legacy.set('subject',JSON.stringify({...qam,credit:1.25,rows:qam.rows.filter(r=>/^PGP[ /]?41[ /]?/i.test(r.roll))}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:legacy})).status,200);const restored=(await (await fetch(base+'/api/subjects',{headers})).json()).subjects.find(s=>s.id===qam.id);assert.equal(restored.rows.length,qam.rows.length);assert.equal(restored.credit,1.25);const scas=data.subjects.find(s=>s.id==='SCAS');const form=new FormData();form.set('subject',JSON.stringify({...scas,credit:1.5}));form.set('pdf',new File([await fs.readFile(sample)],'SCAS.pdf',{type:'application/pdf'}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:form})).status,200);
 const pdfPath=base+'/api/subjects/'+encodeURIComponent(scas.id)+'/pdf';assert.equal((await fetch(pdfPath)).status,401);const pdfResponse=await fetch(pdfPath,{headers});assert.equal(pdfResponse.status,200);assert.deepEqual(Buffer.from(await pdfResponse.arrayBuffer()),await fs.readFile(sample));
 const extended=new FormData();extended.set('subject',JSON.stringify({...qam,rows:[...qam.rows,{...qam.rows[0],roll:'EXEC-2026-7',name:'Extra student'}]}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:extended})).status,200);assert.equal((await (await fetch(base+'/api/subjects',{headers})).json()).subjects.find(s=>s.id===qam.id).rows.length,qam.rows.length+1);
 const mixed={id:'test-mixed-rolls',name:'Validation test',term:4,credit:1,columns:['First','Second'],source:'test.pdf',rows:[{roll:'ABM 22 / 010',name:'Test One',section:'A',total:45,components:[null,45]},{roll:'PGP40/138R',name:'Test Two',section:'B',total:60,components:[20,40]},{roll:'PGP41221',name:'Test Three',section:'A',total:50,components:[25,25]}]};
 const mixedForm=new FormData();mixedForm.set('subject',JSON.stringify(mixed));const mixedResponse=await fetch(base+'/api/subjects',{headers,method:'POST',body:mixedForm});assert.equal(mixedResponse.status,200);assert.deepEqual((await mixedResponse.json()).subject.rows.map(r=>r.roll),['ABM/22/010','PGP/40/138R','PGP/41/221']);
 const invalid=new FormData();invalid.set('subject',JSON.stringify({...mixed,rows:mixed.rows.map((r,i)=>i===1?{...r,components:[20]}:r)}));const invalidResponse=await fetch(base+'/api/subjects',{headers,method:'POST',body:invalid});assert.equal(invalidResponse.status,400);assert.match((await invalidResponse.json()).error,/Student row 2.*expected 2 mark components; found 1/);
 const empty=new FormData();empty.set('subject',JSON.stringify({id:'test-unlimited',name:'Custom elective',term:12,credit:25,rows:[],columns:[],source:'',updatedAt:null}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:empty})).status,200);
 const esgmr=new FormData();esgmr.set('subject',JSON.stringify({id:'test-esgmr',name:'ESGMR',term:5,credit:0,rows:[],columns:[],source:'',updatedAt:null}));const esgmrResponse=await fetch(base+'/api/subjects',{headers,method:'POST',body:esgmr});assert.equal(esgmrResponse.status,200);const esgmrSaved=(await esgmrResponse.json()).subject;assert.equal(esgmrSaved.term,4);assert.equal(esgmrSaved.credit,1);
 await stop();await start();const second=await (await fetch(base+'/api/subjects',{headers})).json();assert.equal(second.subjects.find(s=>s.id==='SCAS').credit,1.5);assert.equal(second.subjects.find(s=>s.id==='test-unlimited').credit,25);assert.equal(second.subjects.find(s=>s.id==='test-unlimited').term,12);assert.equal(second.subjects.find(s=>s.id==='test-esgmr').term,4);assert.equal(second.subjects.find(s=>s.id==='SCAS').rows.length,117);assert.equal((await fs.readdir(temp)).filter(p=>p.endsWith('.pdf')).length,1);
 const bad=new FormData();bad.set('subject',JSON.stringify({...scas,credit:-1}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:bad})).status,400);assert.equal((await fetch(base+'/api/subjects',{headers:{...headers,Origin:'https://example.com'}})).status,403);
 const deleteForm=new FormData();deleteForm.set('subject',JSON.stringify({...scas,id:'test-delete',name:'Duplicate test'}));deleteForm.set('pdf',new File([await fs.readFile(sample)],'duplicate.pdf',{type:'application/pdf'}));assert.equal((await fetch(base+'/api/subjects',{headers,method:'POST',body:deleteForm})).status,200);
 const beforeDelete=(await (await fetch(base+'/api/subjects',{headers})).json()).subjects;
 const deletePath=base+'/api/subjects/test-delete';assert.equal((await fetch(deletePath,{method:'DELETE'})).status,401);assert.equal((await fetch(deletePath,{method:'DELETE',headers:{...headers,Origin:'https://example.com'}})).status,403);assert.equal((await fetch(base+'/api/subjects/SCAS',{method:'DELETE',headers})).status,400);
 const deleted=await fetch(deletePath,{method:'DELETE',headers});assert.equal(deleted.status,200);assert(deleted.headers.get('access-control-allow-methods').includes('DELETE'));assert.deepEqual(await deleted.json(),{deletedId:'test-delete'});
 assert.deepEqual((await (await fetch(base+'/api/subjects',{headers})).json()).subjects,beforeDelete.filter(s=>s.id!=='test-delete'));assert.equal((await fetch(deletePath,{method:'DELETE',headers})).status,404);assert.equal((await fetch(deletePath+'/pdf',{headers})).status,404);assert.equal((await fs.readdir(temp)).filter(p=>p.endsWith('.pdf')).length,1);
 await stop();await start();assert.deepEqual((await (await fetch(base+'/api/subjects',{headers})).json()).subjects,beforeDelete.filter(s=>s.id!=='test-delete'));
 console.log('Passed: existing backend checks plus authenticated subject deletion, PDF removal, workbook protection, persistence and unchanged remaining subjects.');
}finally{if(child&&!child.killed)await stop();await fs.rm(temp,{recursive:true,force:true});}
