import assert from 'node:assert/strict';
import {studentReport,weightedGpa,validateSubject,applyReportCredits} from '../lib/grades.ts';
const row=(name,total,i)=>({name,total,roll:'PGP/41/'+i,components:[],section:''});
const subject=(id,term,credit,rows,name=id)=>({id,name,term,credit,rows,columns:[],source:'test.pdf',updatedAt:null});
const subjects=[subject('ESGMR',5,0,[row('Student One',40,1),row('Other',20,2)]),subject('New elective',7,2,[row(' STUDENT   ONE ',10,1),row('Other',20,2)]),subject('Absent subject',4,10,[row('Other',10,2)]),subject('Pending',8,1,[]),subject('Non-credit',4,0,[row('Student One',10,1)]),subject('New elective 2',7,1,[row('Student One',40,1),row('Other',10,2)])];
const report=studentReport(subjects,'Student One');assert.equal(report.length,4);
assert.equal(report.find(s=>s.name==='ESGMR').term,4);assert.equal(report.find(s=>s.name==='ESGMR').credit,1);
assert(report.every(s=>s.result.grade&&Number.isFinite(s.result.point)));
assert.equal(report.find(s=>s.name==='Non-credit').result.percentile,.5);
assert.equal(report.find(s=>s.name==='Non-credit').result.grade,'B');
const entries=report.map(s=>({credit:s.credit,point:s.result.point}));
assert.equal(weightedGpa(entries),entries.reduce((a,e)=>a+e.credit*e.point,0)/4);
const term7=report.filter(s=>s.term===7),term4=report.filter(s=>s.term===4);
const cgpa=weightedGpa([term4,term7].map(list=>({credit:list.reduce((a,s)=>a+s.credit,0),point:weightedGpa(list.map(s=>({credit:s.credit,point:s.result.point})))})));
assert.equal(cgpa,weightedGpa(entries));
assert.equal(applyReportCredits(subjects).length,subjects.length);
assert.equal(applyReportCredits([subject('ECT',4,2,[])])[0].credit,2);
validateSubject(subject('New empty subject',20,25,[]));
validateSubject(subject('One student',7,25,[row('Student One',2000,1)]));
validateSubject({...subject('Large subject',20,25,Array.from({length:2001},(_,i)=>({...row('Test '+i,2000,i),components:Array(31).fill(2000)}))),columns:Array(31).fill('Mark')});
assert.throws(()=>validateSubject(subject('Invalid',0,-1,[])),/non-negative/);
console.log('Passed: all matching subjects, name spacing, zero-credit grades, ESGMR migration, weighted term and cumulative GPA, pending exclusions, single-student grades and removed subject/term/credit/row/component limits.');
